import type { VideoSpec } from "./schema";

/** Demo spec exercising all 7 block types — validates the data-driven engine. */
export const demoSpec: VideoSpec = {
  id: "explainer-demo",
  brand: {
    titlePre: "Explainer",
    titlePost: "引擎測試",
    name: "Explainer 引擎",
    tagline: "資料驅動 — 每天只產 JSON、不寫新程式碼",
    date: "2026-06-20",
  },
  script: {
    "cv1": "這是資料驅動影片引擎的測試。",
    "cv2": "整支片都從一份 JSON 算出來。",
    "cv3": "七種場景積木，一次驗證。",
    "t1": "第一種：終端機場景。",
    "t2": "可以顯示指令與輸出。",
    "t3": "右邊還能蓋上判定章。",
    "t4": "底部給一句結論。",
    "c1": "第二種：好壞對照。",
    "c2": "左邊是不建議的做法。",
    "c3": "右邊是建議的做法。",
    "c4": "一眼看懂差別。",
    "p1": "第三種：並排選項。",
    "p2": "適合講「放哪裡／選哪個」。",
    "p3": "每個選項一張卡。",
    "p4": "最後收一句結論。",
    "pl1": "第四種：流程圖。",
    "pl2": "一步一步建立。",
    "pl3": "適合講順序與管線。",
    "im1": "第五種：單張大圖。",
    "im2": "重點時可以放大解說。",
    "im3": "還能加上標註。",
    "ot1": "最後總整理。",
    "ot2": "資料驅動、七種積木。",
    "ot3": "每天只產 JSON。",
    "ot4": "穩定、不會 build 壞。",
    "ot5": "感謝觀看，記得訂閱。",
  },
  scenes: [
    {
      type: "cover",
      titlePre: "Explainer",
      titlePost: "引擎測試",
      terminal: { title: "spec.json", lines: [{ k: "cmt", t: "一份 JSON" }, { k: "cmd", t: "render Explainer" }, { k: "ok", t: "七種場景一次到位" }] },
      chips: [{ n: "1", t: "終端機", accent: "green" }, { n: "2", t: "對照", accent: "warn" }, { n: "3", t: "選項", accent: "violet" }, { n: "4", t: "流程/圖", accent: "claude" }],
      cues: ["cv1", "cv2", "cv3"],
    },
    {
      type: "terminal",
      kicker: "場景 01 · 終端機",
      accent: "green",
      headingZh: "終端機場景",
      headingEn: "Terminal scene",
      terminal: { title: "Terminal — zsh", lines: [{ k: "cmd", t: "npm run something" }, { k: "out", t: "working…" }, { k: "ok", t: "done" }] },
      stamps: [{ kind: "warn", text: "⚠ 注意這個", atCue: 2 }, { kind: "yes", text: "✔ 這樣就對", atCue: 3 }],
      keyline: "終端機場景：指令＋輸出＋判定章＋結論",
      keylineAtCue: 3,
      cues: ["t1", "t2", "t3", "t4"],
    },
    {
      type: "compare",
      kicker: "場景 02 · 對照",
      accent: "warn",
      headingZh: "好壞對照",
      headingEn: "Good vs bad",
      bad: { badge: "不建議", code: "do_it_wrong()", note: "問題在這裡" },
      good: { badge: "建議", code: "do_it_right()", note: "這樣比較穩" },
      keyline: "好壞對照：左✘右✔，一眼看懂",
      keylineAtCue: 3,
      cues: ["c1", "c2", "c3", "c4"],
    },
    {
      type: "places",
      kicker: "場景 03 · 選項",
      accent: "violet",
      headingZh: "並排選項",
      headingEn: "Options side by side",
      items: [
        { icon: "🌍", title: "選項 A", path: "~/a", note: "說明 A", accent: "blue" },
        { icon: "📦", title: "選項 B", path: "./b", note: "說明 B", accent: "green" },
        { icon: "🔌", title: "選項 C", path: "plugin", note: "說明 C", accent: "claude" },
      ],
      keyline: "並排選項：每個一張卡＋結論",
      keylineAtCue: 3,
      cues: ["p1", "p2", "p3", "p4"],
    },
    {
      type: "pipeline",
      kicker: "場景 04 · 流程圖",
      accent: "blue",
      headingZh: "流程圖 Pipeline",
      headingEn: "Step-by-step pipeline",
      nodes: [
        { icon: "📝", label: "步驟一", accent: "blue" },
        { icon: "⚙️", label: "步驟二", accent: "green" },
        { icon: "🚀", label: "步驟三", accent: "claude" },
      ],
      keyline: "流程圖：一步步建立順序",
      keylineAtCue: 2,
      cues: ["pl1", "pl2", "pl3"],
    },
    {
      type: "image",
      kicker: "場景 05 · 大圖",
      accent: "claude",
      headingZh: "單張大圖／截圖",
      headingEn: "Big image with zoom",
      src: "explainer-demo.png",
      caption: "重點時可放大解說、加標註",
      focus: { x: 0.3, y: 0.5, scale: 1.6, atCue: 1 },
      annotations: [{ x: 0.3, y: 0.5, text: "看這裡", atCue: 2 }],
      keyline: "大圖＋放大解說＋標註",
      cues: ["im1", "im2", "im3"],
    },
    {
      type: "outro",
      headingZh: "總整理",
      headingEn: "Recap",
      cards: [
        { emoji: "🧱", text: "七種場景積木", accent: "green" },
        { emoji: "📄", text: "每天只產 JSON", accent: "violet" },
        { emoji: "✅", text: "穩定、不會 build 壞", accent: "claude" },
      ],
      cues: ["ot1", "ot2", "ot3", "ot4", "ot5"],
    },
  ],
};
